name: counter_to_sink_can_real_tuned_image

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    robot0_agentview_left_image:
      shape: [3, 128, 128]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 128, 128]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [1]
  action: 
    shape: [7]

dataset_path: &dataset_path /home/abhim/robocasa/deoxys_hdf5s/CounterToSinkCan/demo_tuned/demo.hdf5 
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.real_robomimic_image_runner.RealRobomimicImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02